# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class ApiResourceDetails(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, source_url: str=None, region: str=None, account: str=None, environment_name: str=None, component_name: str=None, toolchain_url: str=None):
        """
        ApiResourceDetails - a model defined in Swagger

        :param source_url: The source_url of this ApiResourceDetails.
        :type source_url: str
        :param region: The region of this ApiResourceDetails.
        :type region: str
        :param account: The account of this ApiResourceDetails.
        :type account: str
        :param environment_name: The environment_name of this ApiResourceDetails.
        :type environment_name: str
        :param component_name: The component_name of this ApiResourceDetails.
        :type component_name: str
        :param toolchain_url: The toolchain_url of this ApiResourceDetails.
        :type toolchain_url: str
        """
        self.swagger_types = {
            'source_url': str,
            'region': str,
            'account': str,
            'environment_name': str,
            'component_name': str,
            'toolchain_url': str
        }

        self.attribute_map = {
            'source_url': 'source_url',
            'region': 'region',
            'account': 'account',
            'environment_name': 'environment_name',
            'component_name': 'component_name',
            'toolchain_url': 'toolchain_url'
        }

        self._source_url = source_url
        self._region = region
        self._account = account
        self._environment_name = environment_name
        self._component_name = component_name
        self._toolchain_url = toolchain_url

    @classmethod
    def from_dict(cls, dikt) -> 'ApiResourceDetails':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The apiResourceDetails of this ApiResourceDetails.
        :rtype: ApiResourceDetails
        """
        return deserialize_model(dikt, cls)

    @property
    def source_url(self) -> str:
        """
        Gets the source_url of this ApiResourceDetails.
        The unique url of the source (e.g. service, app) of the occurrence

        :return: The source_url of this ApiResourceDetails.
        :rtype: str
        """
        return self._source_url

    @source_url.setter
    def source_url(self, source_url: str):
        """
        Sets the source_url of this ApiResourceDetails.
        The unique url of the source (e.g. service, app) of the occurrence

        :param source_url: The source_url of this ApiResourceDetails.
        :type source_url: str
        """

        self._source_url = source_url

    @property
    def region(self) -> str:
        """
        Gets the region of this ApiResourceDetails.
        The region the resource belongs to

        :return: The region of this ApiResourceDetails.
        :rtype: str
        """
        return self._region

    @region.setter
    def region(self, region: str):
        """
        Sets the region of this ApiResourceDetails.
        The region the resource belongs to

        :param region: The region of this ApiResourceDetails.
        :type region: str
        """

        self._region = region

    @property
    def account(self) -> str:
        """
        Gets the account of this ApiResourceDetails.
        The account the resource belongs to

        :return: The account of this ApiResourceDetails.
        :rtype: str
        """
        return self._account

    @account.setter
    def account(self, account: str):
        """
        Sets the account of this ApiResourceDetails.
        The account the resource belongs to

        :param account: The account of this ApiResourceDetails.
        :type account: str
        """

        self._account = account

    @property
    def environment_name(self) -> str:
        """
        Gets the environment_name of this ApiResourceDetails.
        The name of the logical environment the resource is linked to

        :return: The environment_name of this ApiResourceDetails.
        :rtype: str
        """
        return self._environment_name

    @environment_name.setter
    def environment_name(self, environment_name: str):
        """
        Sets the environment_name of this ApiResourceDetails.
        The name of the logical environment the resource is linked to

        :param environment_name: The environment_name of this ApiResourceDetails.
        :type environment_name: str
        """

        self._environment_name = environment_name

    @property
    def component_name(self) -> str:
        """
        Gets the component_name of this ApiResourceDetails.
        The name of the logical component the resource is linked to

        :return: The component_name of this ApiResourceDetails.
        :rtype: str
        """
        return self._component_name

    @component_name.setter
    def component_name(self, component_name: str):
        """
        Sets the component_name of this ApiResourceDetails.
        The name of the logical component the resource is linked to

        :param component_name: The component_name of this ApiResourceDetails.
        :type component_name: str
        """

        self._component_name = component_name

    @property
    def toolchain_url(self) -> str:
        """
        Gets the toolchain_url of this ApiResourceDetails.
        The url of the toolchain the resource is linked to

        :return: The toolchain_url of this ApiResourceDetails.
        :rtype: str
        """
        return self._toolchain_url

    @toolchain_url.setter
    def toolchain_url(self, toolchain_url: str):
        """
        Sets the toolchain_url of this ApiResourceDetails.
        The url of the toolchain the resource is linked to

        :param toolchain_url: The toolchain_url of this ApiResourceDetails.
        :type toolchain_url: str
        """

        self._toolchain_url = toolchain_url

