# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.api_hash import ApiHash
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class ApiFileHashes(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, file_hash: List[ApiHash]=None):
        """
        ApiFileHashes - a model defined in Swagger

        :param file_hash: The file_hash of this ApiFileHashes.
        :type file_hash: List[ApiHash]
        """
        self.swagger_types = {
            'file_hash': List[ApiHash]
        }

        self.attribute_map = {
            'file_hash': 'file_hash'
        }

        self._file_hash = file_hash

    @classmethod
    def from_dict(cls, dikt) -> 'ApiFileHashes':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The apiFileHashes of this ApiFileHashes.
        :rtype: ApiFileHashes
        """
        return deserialize_model(dikt, cls)

    @property
    def file_hash(self) -> List[ApiHash]:
        """
        Gets the file_hash of this ApiFileHashes.
        Collection of file hashes.

        :return: The file_hash of this ApiFileHashes.
        :rtype: List[ApiHash]
        """
        return self._file_hash

    @file_hash.setter
    def file_hash(self, file_hash: List[ApiHash]):
        """
        Sets the file_hash of this ApiFileHashes.
        Collection of file hashes.

        :param file_hash: The file_hash of this ApiFileHashes.
        :type file_hash: List[ApiHash]
        """

        self._file_hash = file_hash

