# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.api_project import ApiProject
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class ApiListProjectsResponse(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, projects: List[ApiProject]=None, next_page_token: str=None):
        """
        ApiListProjectsResponse - a model defined in Swagger

        :param projects: The projects of this ApiListProjectsResponse.
        :type projects: List[ApiProject]
        :param next_page_token: The next_page_token of this ApiListProjectsResponse.
        :type next_page_token: str
        """
        self.swagger_types = {
            'projects': List[ApiProject],
            'next_page_token': str
        }

        self.attribute_map = {
            'projects': 'projects',
            'next_page_token': 'next_page_token'
        }

        self._projects = projects
        self._next_page_token = next_page_token

    @classmethod
    def from_dict(cls, dikt) -> 'ApiListProjectsResponse':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The apiListProjectsResponse of this ApiListProjectsResponse.
        :rtype: ApiListProjectsResponse
        """
        return deserialize_model(dikt, cls)

    @property
    def projects(self) -> List[ApiProject]:
        """
        Gets the projects of this ApiListProjectsResponse.
        The projects requested.

        :return: The projects of this ApiListProjectsResponse.
        :rtype: List[ApiProject]
        """
        return self._projects

    @projects.setter
    def projects(self, projects: List[ApiProject]):
        """
        Sets the projects of this ApiListProjectsResponse.
        The projects requested.

        :param projects: The projects of this ApiListProjectsResponse.
        :type projects: List[ApiProject]
        """

        self._projects = projects

    @property
    def next_page_token(self) -> str:
        """
        Gets the next_page_token of this ApiListProjectsResponse.
        The next pagination token in the list response. It should be used as `page_token` for the following request. An empty value means no more results.

        :return: The next_page_token of this ApiListProjectsResponse.
        :rtype: str
        """
        return self._next_page_token

    @next_page_token.setter
    def next_page_token(self, next_page_token: str):
        """
        Sets the next_page_token of this ApiListProjectsResponse.
        The next pagination token in the list response. It should be used as `page_token` for the following request. An empty value means no more results.

        :param next_page_token: The next_page_token of this ApiListProjectsResponse.
        :type next_page_token: str
        """

        self._next_page_token = next_page_token

