# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.api_occurrence import ApiOccurrence
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class ApiListNoteOccurrencesResponse(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, occurrences: List[ApiOccurrence]=None, next_page_token: str=None):
        """
        ApiListNoteOccurrencesResponse - a model defined in Swagger

        :param occurrences: The occurrences of this ApiListNoteOccurrencesResponse.
        :type occurrences: List[ApiOccurrence]
        :param next_page_token: The next_page_token of this ApiListNoteOccurrencesResponse.
        :type next_page_token: str
        """
        self.swagger_types = {
            'occurrences': List[ApiOccurrence],
            'next_page_token': str
        }

        self.attribute_map = {
            'occurrences': 'occurrences',
            'next_page_token': 'next_page_token'
        }

        self._occurrences = occurrences
        self._next_page_token = next_page_token

    @classmethod
    def from_dict(cls, dikt) -> 'ApiListNoteOccurrencesResponse':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The apiListNoteOccurrencesResponse of this ApiListNoteOccurrencesResponse.
        :rtype: ApiListNoteOccurrencesResponse
        """
        return deserialize_model(dikt, cls)

    @property
    def occurrences(self) -> List[ApiOccurrence]:
        """
        Gets the occurrences of this ApiListNoteOccurrencesResponse.
        The occurrences attached to the specified note.

        :return: The occurrences of this ApiListNoteOccurrencesResponse.
        :rtype: List[ApiOccurrence]
        """
        return self._occurrences

    @occurrences.setter
    def occurrences(self, occurrences: List[ApiOccurrence]):
        """
        Sets the occurrences of this ApiListNoteOccurrencesResponse.
        The occurrences attached to the specified note.

        :param occurrences: The occurrences of this ApiListNoteOccurrencesResponse.
        :type occurrences: List[ApiOccurrence]
        """

        self._occurrences = occurrences

    @property
    def next_page_token(self) -> str:
        """
        Gets the next_page_token of this ApiListNoteOccurrencesResponse.
        Token to receive the next page of notes.

        :return: The next_page_token of this ApiListNoteOccurrencesResponse.
        :rtype: str
        """
        return self._next_page_token

    @next_page_token.setter
    def next_page_token(self, next_page_token: str):
        """
        Sets the next_page_token of this ApiListNoteOccurrencesResponse.
        Token to receive the next page of notes.

        :param next_page_token: The next_page_token of this ApiListNoteOccurrencesResponse.
        :type next_page_token: str
        """

        self._next_page_token = next_page_token

