# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class ApiGitSourceContext(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, url: str=None, revision_id: str=None):
        """
        ApiGitSourceContext - a model defined in Swagger

        :param url: The url of this ApiGitSourceContext.
        :type url: str
        :param revision_id: The revision_id of this ApiGitSourceContext.
        :type revision_id: str
        """
        self.swagger_types = {
            'url': str,
            'revision_id': str
        }

        self.attribute_map = {
            'url': 'url',
            'revision_id': 'revision_id'
        }

        self._url = url
        self._revision_id = revision_id

    @classmethod
    def from_dict(cls, dikt) -> 'ApiGitSourceContext':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The apiGitSourceContext of this ApiGitSourceContext.
        :rtype: ApiGitSourceContext
        """
        return deserialize_model(dikt, cls)

    @property
    def url(self) -> str:
        """
        Gets the url of this ApiGitSourceContext.
        Git repository URL.

        :return: The url of this ApiGitSourceContext.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """
        Sets the url of this ApiGitSourceContext.
        Git repository URL.

        :param url: The url of this ApiGitSourceContext.
        :type url: str
        """

        self._url = url

    @property
    def revision_id(self) -> str:
        """
        Gets the revision_id of this ApiGitSourceContext.
        Required. Git commit hash.

        :return: The revision_id of this ApiGitSourceContext.
        :rtype: str
        """
        return self._revision_id

    @revision_id.setter
    def revision_id(self, revision_id: str):
        """
        Sets the revision_id of this ApiGitSourceContext.
        Required. Git commit hash.

        :param revision_id: The revision_id of this ApiGitSourceContext.
        :type revision_id: str
        """

        self._revision_id = revision_id

