# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class ApiDeployable(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, resource_uri: List[str]=None):
        """
        ApiDeployable - a model defined in Swagger

        :param resource_uri: The resource_uri of this ApiDeployable.
        :type resource_uri: List[str]
        """
        self.swagger_types = {
            'resource_uri': List[str]
        }

        self.attribute_map = {
            'resource_uri': 'resource_uri'
        }

        self._resource_uri = resource_uri

    @classmethod
    def from_dict(cls, dikt) -> 'ApiDeployable':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The apiDeployable of this ApiDeployable.
        :rtype: ApiDeployable
        """
        return deserialize_model(dikt, cls)

    @property
    def resource_uri(self) -> List[str]:
        """
        Gets the resource_uri of this ApiDeployable.
        Resource URI for the artifact being deployed.

        :return: The resource_uri of this ApiDeployable.
        :rtype: List[str]
        """
        return self._resource_uri

    @resource_uri.setter
    def resource_uri(self, resource_uri: List[str]):
        """
        Sets the resource_uri of this ApiDeployable.
        Resource URI for the artifact being deployed.

        :param resource_uri: The resource_uri of this ApiDeployable.
        :type resource_uri: List[str]
        """

        self._resource_uri = resource_uri

