# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.api_build_signature import ApiBuildSignature
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class ApiBuildType(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, builder_version: str=None, signature: ApiBuildSignature=None):
        """
        ApiBuildType - a model defined in Swagger

        :param builder_version: The builder_version of this ApiBuildType.
        :type builder_version: str
        :param signature: The signature of this ApiBuildType.
        :type signature: ApiBuildSignature
        """
        self.swagger_types = {
            'builder_version': str,
            'signature': ApiBuildSignature
        }

        self.attribute_map = {
            'builder_version': 'builder_version',
            'signature': 'signature'
        }

        self._builder_version = builder_version
        self._signature = signature

    @classmethod
    def from_dict(cls, dikt) -> 'ApiBuildType':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The apiBuildType of this ApiBuildType.
        :rtype: ApiBuildType
        """
        return deserialize_model(dikt, cls)

    @property
    def builder_version(self) -> str:
        """
        Gets the builder_version of this ApiBuildType.
        Version of the builder which produced this Note.

        :return: The builder_version of this ApiBuildType.
        :rtype: str
        """
        return self._builder_version

    @builder_version.setter
    def builder_version(self, builder_version: str):
        """
        Sets the builder_version of this ApiBuildType.
        Version of the builder which produced this Note.

        :param builder_version: The builder_version of this ApiBuildType.
        :type builder_version: str
        """

        self._builder_version = builder_version

    @property
    def signature(self) -> ApiBuildSignature:
        """
        Gets the signature of this ApiBuildType.
        Signature of the build in Occurrences pointing to the Note containing this `BuilderDetails`.

        :return: The signature of this ApiBuildType.
        :rtype: ApiBuildSignature
        """
        return self._signature

    @signature.setter
    def signature(self, signature: ApiBuildSignature):
        """
        Sets the signature of this ApiBuildType.
        Signature of the build in Occurrences pointing to the Note containing this `BuilderDetails`.

        :param signature: The signature of this ApiBuildType.
        :type signature: ApiBuildSignature
        """

        self._signature = signature

