# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.api_certainty import ApiCertainty
from swagger_server.models.api_note_kind import ApiNoteKind
from swagger_server.models.api_resource_details import ApiResourceDetails
from swagger_server.models.api_severity import ApiSeverity
from swagger_server.models.security_finding import SecurityFinding
from swagger_server.models.vulnerability_type_vulnerability_details import VulnerabilityTypeVulnerabilityDetails
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class ApiOccurrence(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, name: str=None, resource_url: str=None, note_name: str=None, kind: ApiNoteKind=None, remediation: str=None, create_time: datetime=None, update_time: datetime=None, vulnerability_details: VulnerabilityTypeVulnerabilityDetails=None, short_description: str=None, long_description: str=None, resource_details: ApiResourceDetails=None, severity: ApiSeverity=None, certainty: ApiCertainty=None, security_finding_details: SecurityFinding=None):
        """
        ApiOccurrence - a model defined in Swagger

        :param name: The name of this ApiOccurrence.
        :type name: str
        :param resource_url: The resource_url of this ApiOccurrence.
        :type resource_url: str
        :param note_name: The note_name of this ApiOccurrence.
        :type note_name: str
        :param kind: The kind of this ApiOccurrence.
        :type kind: ApiNoteKind
        :param remediation: The remediation of this ApiOccurrence.
        :type remediation: str
        :param create_time: The create_time of this ApiOccurrence.
        :type create_time: datetime
        :param update_time: The update_time of this ApiOccurrence.
        :type update_time: datetime
        :param vulnerability_details: The vulnerability_details of this ApiOccurrence.
        :type vulnerability_details: VulnerabilityTypeVulnerabilityDetails
        :param short_description: The short_description of this ApiOccurrence.
        :type short_description: str
        :param long_description: The long_description of this ApiOccurrence.
        :type long_description: str
        :param resource_details: The resource_details of this ApiOccurrence.
        :type resource_details: ApiResourceDetails
        :param severity: The severity of this ApiOccurrence.
        :type severity: ApiSeverity
        :param certainty: The certainty of this ApiOccurrence.
        :type certainty: ApiCertainty
        :param security_finding_details: The security_finding_details of this ApiOccurrence.
        :type security_finding_details: SecurityFinding
        """
        self.swagger_types = {
            'name': str,
            'resource_url': str,
            'note_name': str,
            'kind': ApiNoteKind,
            'remediation': str,
            'create_time': datetime,
            'update_time': datetime,
            'vulnerability_details': VulnerabilityTypeVulnerabilityDetails,
            'short_description': str,
            'long_description': str,
            'resource_details': ApiResourceDetails,
            'severity': ApiSeverity,
            'certainty': ApiCertainty,
            'security_finding_details': SecurityFinding
        }

        self.attribute_map = {
            'name': 'name',
            'resource_url': 'resource_url',
            'note_name': 'note_name',
            'kind': 'kind',
            'remediation': 'remediation',
            'create_time': 'create_time',
            'update_time': 'update_time',
            'vulnerability_details': 'vulnerability_details',
            'short_description': 'short_description',
            'long_description': 'long_description',
            'resource_details': 'resource_details',
            'severity': 'severity',
            'certainty': 'certainty',
            'security_finding_details': 'security_finding_details'
        }

        self._name = name
        self._resource_url = resource_url
        self._note_name = note_name
        self._kind = kind
        self._remediation = remediation
        self._create_time = create_time
        self._update_time = update_time
        self._vulnerability_details = vulnerability_details
        self._short_description = short_description
        self._long_description = long_description
        self._resource_details = resource_details
        self._severity = severity
        self._certainty = certainty
        self._security_finding_details = security_finding_details

    @classmethod
    def from_dict(cls, dikt) -> 'ApiOccurrence':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The apiOccurrence of this ApiOccurrence.
        :rtype: ApiOccurrence
        """
        return deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """
        Gets the name of this ApiOccurrence.
        Output only. The name of the `Occurrence` in the form \"projects/{projectId}/occurrences/{occuurenceId}\"

        :return: The name of this ApiOccurrence.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """
        Sets the name of this ApiOccurrence.
        Output only. The name of the `Occurrence` in the form \"projects/{projectId}/occurrences/{occuurenceId}\"

        :param name: The name of this ApiOccurrence.
        :type name: str
        """

        self._name = name

    @property
    def resource_url(self) -> str:
        """
        Gets the resource_url of this ApiOccurrence.
        The unique URL of the resource, image or the container, for which the `Occurrence` applies. For example, https://gcr.io/project/image@sha256:foo. This field can be used as a filter in list requests.

        :return: The resource_url of this ApiOccurrence.
        :rtype: str
        """
        return self._resource_url

    @resource_url.setter
    def resource_url(self, resource_url: str):
        """
        Sets the resource_url of this ApiOccurrence.
        The unique URL of the resource, image or the container, for which the `Occurrence` applies. For example, https://gcr.io/project/image@sha256:foo. This field can be used as a filter in list requests.

        :param resource_url: The resource_url of this ApiOccurrence.
        :type resource_url: str
        """

        self._resource_url = resource_url

    @property
    def note_name(self) -> str:
        """
        Gets the note_name of this ApiOccurrence.
        An analysis note associated with this image, in the form \"projects/{projectId}/notes/{noteId}\" This field can be used as a filter in list requests.

        :return: The note_name of this ApiOccurrence.
        :rtype: str
        """
        return self._note_name

    @note_name.setter
    def note_name(self, note_name: str):
        """
        Sets the note_name of this ApiOccurrence.
        An analysis note associated with this image, in the form \"projects/{projectId}/notes/{noteId}\" This field can be used as a filter in list requests.

        :param note_name: The note_name of this ApiOccurrence.
        :type note_name: str
        """

        self._note_name = note_name

    @property
    def kind(self) -> ApiNoteKind:
        """
        Gets the kind of this ApiOccurrence.
        Output only. This explicitly denotes which of the `Occurrence` details are specified. This field can be used as a filter in list requests.

        :return: The kind of this ApiOccurrence.
        :rtype: ApiNoteKind
        """
        return self._kind

    @kind.setter
    def kind(self, kind: ApiNoteKind):
        """
        Sets the kind of this ApiOccurrence.
        Output only. This explicitly denotes which of the `Occurrence` details are specified. This field can be used as a filter in list requests.

        :param kind: The kind of this ApiOccurrence.
        :type kind: ApiNoteKind
        """

        self._kind = kind

    @property
    def remediation(self) -> str:
        """
        Gets the remediation of this ApiOccurrence.

        :return: The remediation of this ApiOccurrence.
        :rtype: str
        """
        return self._remediation

    @remediation.setter
    def remediation(self, remediation: str):
        """
        Sets the remediation of this ApiOccurrence.

        :param remediation: The remediation of this ApiOccurrence.
        :type remediation: str
        """

        self._remediation = remediation

    @property
    def create_time(self) -> datetime:
        """
        Gets the create_time of this ApiOccurrence.
        Output only. The time this `Occurrence` was created.

        :return: The create_time of this ApiOccurrence.
        :rtype: datetime
        """
        return self._create_time

    @create_time.setter
    def create_time(self, create_time: datetime):
        """
        Sets the create_time of this ApiOccurrence.
        Output only. The time this `Occurrence` was created.

        :param create_time: The create_time of this ApiOccurrence.
        :type create_time: datetime
        """

        self._create_time = create_time

    @property
    def update_time(self) -> datetime:
        """
        Gets the update_time of this ApiOccurrence.
        Output only. The time this `Occurrence` was last updated.

        :return: The update_time of this ApiOccurrence.
        :rtype: datetime
        """
        return self._update_time

    @update_time.setter
    def update_time(self, update_time: datetime):
        """
        Sets the update_time of this ApiOccurrence.
        Output only. The time this `Occurrence` was last updated.

        :param update_time: The update_time of this ApiOccurrence.
        :type update_time: datetime
        """

        self._update_time = update_time

    @property
    def vulnerability_details(self) -> VulnerabilityTypeVulnerabilityDetails:
        """
        Gets the vulnerability_details of this ApiOccurrence.
        Details of the occurrence of a security vulnerability.

        :return: The vulnerability_details of this ApiOccurrence.
        :rtype: VulnerabilityTypeVulnerabilityDetails
        """
        return self._vulnerability_details

    @vulnerability_details.setter
    def vulnerability_details(self, vulnerability_details: VulnerabilityTypeVulnerabilityDetails):
        """
        Sets the vulnerability_details of this ApiOccurrence.
        Details of the occurrence of a security vulnerability.

        :param vulnerability_details: The vulnerability_details of this ApiOccurrence.
        :type vulnerability_details: VulnerabilityTypeVulnerabilityDetails
        """

        self._vulnerability_details = vulnerability_details

    @property
    def short_description(self) -> str:
        """
        Gets the short_description of this ApiOccurrence.
        A one sentence description of this `Occurrence`.

        :return: The short_description of this ApiOccurrence.
        :rtype: str
        """
        return self._short_description

    @short_description.setter
    def short_description(self, short_description: str):
        """
        Sets the short_description of this ApiOccurrence.
        A one sentence description of this `Occurrence`.

        :param short_description: The short_description of this ApiOccurrence.
        :type short_description: str
        """

        self._short_description = short_description

    @property
    def long_description(self) -> str:
        """
        Gets the long_description of this ApiOccurrence.
        A detailed description of this `Occurrence`.

        :return: The long_description of this ApiOccurrence.
        :rtype: str
        """
        return self._long_description

    @long_description.setter
    def long_description(self, long_description: str):
        """
        Sets the long_description of this ApiOccurrence.
        A detailed description of this `Occurrence`.

        :param long_description: The long_description of this ApiOccurrence.
        :type long_description: str
        """

        self._long_description = long_description

    @property
    def resource_details(self) -> ApiResourceDetails:
        """
        Gets the resource_details of this ApiOccurrence.
        Details about the resource this `Occurrence` applies to

        :return: The resource_details of this ApiOccurrence.
        :rtype: ApiResourceDetails
        """
        return self._resource_details

    @resource_details.setter
    def resource_details(self, resource_details: ApiResourceDetails):
        """
        Sets the resource_details of this ApiOccurrence.
        Details about the resource this `Occurrence` applies to

        :param resource_details: The resource_details of this ApiOccurrence.
        :type resource_details: ApiResourceDetails
        """

        self._resource_details = resource_details

    @property
    def severity(self) -> ApiSeverity:
        """
        Gets the severity of this ApiOccurrence.
        The common severity of this `Occurrence`

        :return: The severity of this ApiOccurrence.
        :rtype: ApiSeverity
        """
        return self._severity

    @severity.setter
    def severity(self, severity: ApiSeverity):
        """
        Sets the severity of this ApiOccurrence.
        The common severity of this `Occurrence`

        :param severity: The severity of this ApiOccurrence.
        :type severity: ApiSeverity
        """

        self._severity = severity

    @property
    def certainty(self) -> ApiCertainty:
        """
        Gets the certainty of this ApiOccurrence.
        The confidence level on this `Occurrence`

        :return: The certainty of this ApiOccurrence.
        :rtype: ApiCertainty
        """
        return self._certainty

    @certainty.setter
    def certainty(self, certainty: ApiCertainty):
        """
        Sets the certainty of this ApiOccurrence.
        The confidence level on this `Occurrence`

        :param certainty: The certainty of this ApiOccurrence.
        :type certainty: ApiCertainty
        """

        self._certainty = certainty

    @property
    def security_finding_details(self) -> SecurityFinding:
        """
        Gets the security_finding_details of this ApiOccurrence.
        Details of the occurrence of a security finding.

        :return: The security_finding_details of this ApiOccurrence.
        :rtype: SecurityFinding
        """
        return self._security_finding_details

    @security_finding_details.setter
    def security_finding_details(self, security_finding_details: SecurityFinding):
        """
        Sets the security_finding_details of this ApiOccurrence.
        Details of the occurrence of a security finding.

        :param security_finding_details: The security_finding_details of this ApiOccurrence.
        :type security_finding_details: SecurityFinding
        """

        self._security_finding_details = security_finding_details

