# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.vulnerability_type_version import VulnerabilityTypeVersion
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class ApiPackageManagerLocation(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, cpe_uri: str=None, version: VulnerabilityTypeVersion=None, path: str=None):
        """
        ApiPackageManagerLocation - a model defined in Swagger

        :param cpe_uri: The cpe_uri of this ApiPackageManagerLocation.
        :type cpe_uri: str
        :param version: The version of this ApiPackageManagerLocation.
        :type version: VulnerabilityTypeVersion
        :param path: The path of this ApiPackageManagerLocation.
        :type path: str
        """
        self.swagger_types = {
            'cpe_uri': str,
            'version': VulnerabilityTypeVersion,
            'path': str
        }

        self.attribute_map = {
            'cpe_uri': 'cpe_uri',
            'version': 'version',
            'path': 'path'
        }

        self._cpe_uri = cpe_uri
        self._version = version
        self._path = path

    @classmethod
    def from_dict(cls, dikt) -> 'ApiPackageManagerLocation':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The apiPackageManagerLocation of this ApiPackageManagerLocation.
        :rtype: ApiPackageManagerLocation
        """
        return deserialize_model(dikt, cls)

    @property
    def cpe_uri(self) -> str:
        """
        Gets the cpe_uri of this ApiPackageManagerLocation.
        The cpe_uri in [cpe format](https://cpe.mitre.org/specification/) denoting the package manager version distributing a package.

        :return: The cpe_uri of this ApiPackageManagerLocation.
        :rtype: str
        """
        return self._cpe_uri

    @cpe_uri.setter
    def cpe_uri(self, cpe_uri: str):
        """
        Sets the cpe_uri of this ApiPackageManagerLocation.
        The cpe_uri in [cpe format](https://cpe.mitre.org/specification/) denoting the package manager version distributing a package.

        :param cpe_uri: The cpe_uri of this ApiPackageManagerLocation.
        :type cpe_uri: str
        """

        self._cpe_uri = cpe_uri

    @property
    def version(self) -> VulnerabilityTypeVersion:
        """
        Gets the version of this ApiPackageManagerLocation.
        The version installed at this location.

        :return: The version of this ApiPackageManagerLocation.
        :rtype: VulnerabilityTypeVersion
        """
        return self._version

    @version.setter
    def version(self, version: VulnerabilityTypeVersion):
        """
        Sets the version of this ApiPackageManagerLocation.
        The version installed at this location.

        :param version: The version of this ApiPackageManagerLocation.
        :type version: VulnerabilityTypeVersion
        """

        self._version = version

    @property
    def path(self) -> str:
        """
        Gets the path of this ApiPackageManagerLocation.
        The path from which we gathered that this package/version is installed.

        :return: The path of this ApiPackageManagerLocation.
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path: str):
        """
        Sets the path of this ApiPackageManagerLocation.
        The path from which we gathered that this package/version is installed.

        :param path: The path of this ApiPackageManagerLocation.
        :type path: str
        """

        self._path = path

