# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class ApiStorageSource(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, bucket: str=None, object: str=None, generation: str=None):
        """
        ApiStorageSource - a model defined in Swagger

        :param bucket: The bucket of this ApiStorageSource.
        :type bucket: str
        :param object: The object of this ApiStorageSource.
        :type object: str
        :param generation: The generation of this ApiStorageSource.
        :type generation: str
        """
        self.swagger_types = {
            'bucket': str,
            'object': str,
            'generation': str
        }

        self.attribute_map = {
            'bucket': 'bucket',
            'object': 'object',
            'generation': 'generation'
        }

        self._bucket = bucket
        self._object = object
        self._generation = generation

    @classmethod
    def from_dict(cls, dikt) -> 'ApiStorageSource':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The apiStorageSource of this ApiStorageSource.
        :rtype: ApiStorageSource
        """
        return deserialize_model(dikt, cls)

    @property
    def bucket(self) -> str:
        """
        Gets the bucket of this ApiStorageSource.
        Google Cloud Storage bucket containing source (see [Bucket Name Requirements] (https://cloud.google.com/storage/docs/bucket-naming#requirements)).

        :return: The bucket of this ApiStorageSource.
        :rtype: str
        """
        return self._bucket

    @bucket.setter
    def bucket(self, bucket: str):
        """
        Sets the bucket of this ApiStorageSource.
        Google Cloud Storage bucket containing source (see [Bucket Name Requirements] (https://cloud.google.com/storage/docs/bucket-naming#requirements)).

        :param bucket: The bucket of this ApiStorageSource.
        :type bucket: str
        """

        self._bucket = bucket

    @property
    def object(self) -> str:
        """
        Gets the object of this ApiStorageSource.
        Google Cloud Storage object containing source.

        :return: The object of this ApiStorageSource.
        :rtype: str
        """
        return self._object

    @object.setter
    def object(self, object: str):
        """
        Sets the object of this ApiStorageSource.
        Google Cloud Storage object containing source.

        :param object: The object of this ApiStorageSource.
        :type object: str
        """

        self._object = object

    @property
    def generation(self) -> str:
        """
        Gets the generation of this ApiStorageSource.
        Google Cloud Storage generation for the object.

        :return: The generation of this ApiStorageSource.
        :rtype: str
        """
        return self._generation

    @generation.setter
    def generation(self, generation: str):
        """
        Sets the generation of this ApiStorageSource.
        Google Cloud Storage generation for the object.

        :param generation: The generation of this ApiStorageSource.
        :type generation: str
        """

        self._generation = generation

