# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.api_note_kind import ApiNoteKind
from swagger_server.models.api_note_related_url import ApiNoteRelatedUrl
from swagger_server.models.security_finding_type import SecurityFindingType
from swagger_server.models.vulnerability_type import VulnerabilityType
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class ApiNote(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, name: str=None, short_description: str=None, long_description: str=None, kind: ApiNoteKind=None, related_url: List[ApiNoteRelatedUrl]=None, expiration_time: datetime=None, create_time: datetime=None, update_time: datetime=None, vulnerability_type: VulnerabilityType=None, security_finding_type: SecurityFindingType=None):
        """
        ApiNote - a model defined in Swagger

        :param name: The name of this ApiNote.
        :type name: str
        :param short_description: The short_description of this ApiNote.
        :type short_description: str
        :param long_description: The long_description of this ApiNote.
        :type long_description: str
        :param kind: The kind of this ApiNote.
        :type kind: ApiNoteKind
        :param related_url: The related_url of this ApiNote.
        :type related_url: List[ApiNoteRelatedUrl]
        :param expiration_time: The expiration_time of this ApiNote.
        :type expiration_time: datetime
        :param create_time: The create_time of this ApiNote.
        :type create_time: datetime
        :param update_time: The update_time of this ApiNote.
        :type update_time: datetime
        :param vulnerability_type: The vulnerability_type of this ApiNote.
        :type vulnerability_type: VulnerabilityType
        :param security_finding_type: The security_finding_type of this ApiNote.
        :type security_finding_type: SecurityFindingType
        """
        self.swagger_types = {
            'name': str,
            'short_description': str,
            'long_description': str,
            'kind': ApiNoteKind,
            'related_url': List[ApiNoteRelatedUrl],
            'expiration_time': datetime,
            'create_time': datetime,
            'update_time': datetime,
            'vulnerability_type': VulnerabilityType,
            'security_finding_type': SecurityFindingType
        }

        self.attribute_map = {
            'name': 'name',
            'short_description': 'short_description',
            'long_description': 'long_description',
            'kind': 'kind',
            'related_url': 'related_url',
            'expiration_time': 'expiration_time',
            'create_time': 'create_time',
            'update_time': 'update_time',
            'vulnerability_type': 'vulnerability_type',
            'security_finding_type': 'security_finding_type'
        }

        self._name = name
        self._short_description = short_description
        self._long_description = long_description
        self._kind = kind
        self._related_url = related_url
        self._expiration_time = expiration_time
        self._create_time = create_time
        self._update_time = update_time
        self._vulnerability_type = vulnerability_type
        self._security_finding_type = security_finding_type

    @classmethod
    def from_dict(cls, dikt) -> 'ApiNote':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The apiNote of this ApiNote.
        :rtype: ApiNote
        """
        return deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """
        Gets the name of this ApiNote.

        :return: The name of this ApiNote.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """
        Sets the name of this ApiNote.

        :param name: The name of this ApiNote.
        :type name: str
        """

        self._name = name

    @property
    def short_description(self) -> str:
        """
        Gets the short_description of this ApiNote.
        A one sentence description of this `Note`.

        :return: The short_description of this ApiNote.
        :rtype: str
        """
        return self._short_description

    @short_description.setter
    def short_description(self, short_description: str):
        """
        Sets the short_description of this ApiNote.
        A one sentence description of this `Note`.

        :param short_description: The short_description of this ApiNote.
        :type short_description: str
        """

        self._short_description = short_description

    @property
    def long_description(self) -> str:
        """
        Gets the long_description of this ApiNote.
        A detailed description of this `Note`.

        :return: The long_description of this ApiNote.
        :rtype: str
        """
        return self._long_description

    @long_description.setter
    def long_description(self, long_description: str):
        """
        Sets the long_description of this ApiNote.
        A detailed description of this `Note`.

        :param long_description: The long_description of this ApiNote.
        :type long_description: str
        """

        self._long_description = long_description

    @property
    def kind(self) -> ApiNoteKind:
        """
        Gets the kind of this ApiNote.
        Output only. This explicitly denotes which kind of note is specified. This field can be used as a filter in list requests.

        :return: The kind of this ApiNote.
        :rtype: ApiNoteKind
        """
        return self._kind

    @kind.setter
    def kind(self, kind: ApiNoteKind):
        """
        Sets the kind of this ApiNote.
        Output only. This explicitly denotes which kind of note is specified. This field can be used as a filter in list requests.

        :param kind: The kind of this ApiNote.
        :type kind: ApiNoteKind
        """

        self._kind = kind

    @property
    def related_url(self) -> List[ApiNoteRelatedUrl]:
        """
        Gets the related_url of this ApiNote.

        :return: The related_url of this ApiNote.
        :rtype: List[ApiNoteRelatedUrl]
        """
        return self._related_url

    @related_url.setter
    def related_url(self, related_url: List[ApiNoteRelatedUrl]):
        """
        Sets the related_url of this ApiNote.

        :param related_url: The related_url of this ApiNote.
        :type related_url: List[ApiNoteRelatedUrl]
        """

        self._related_url = related_url

    @property
    def expiration_time(self) -> datetime:
        """
        Gets the expiration_time of this ApiNote.
        Time of expiration for this note, null if note does not expire.

        :return: The expiration_time of this ApiNote.
        :rtype: datetime
        """
        return self._expiration_time

    @expiration_time.setter
    def expiration_time(self, expiration_time: datetime):
        """
        Sets the expiration_time of this ApiNote.
        Time of expiration for this note, null if note does not expire.

        :param expiration_time: The expiration_time of this ApiNote.
        :type expiration_time: datetime
        """

        self._expiration_time = expiration_time

    @property
    def create_time(self) -> datetime:
        """
        Gets the create_time of this ApiNote.
        Output only. The time this note was created. This field can be used as a filter in list requests.

        :return: The create_time of this ApiNote.
        :rtype: datetime
        """
        return self._create_time

    @create_time.setter
    def create_time(self, create_time: datetime):
        """
        Sets the create_time of this ApiNote.
        Output only. The time this note was created. This field can be used as a filter in list requests.

        :param create_time: The create_time of this ApiNote.
        :type create_time: datetime
        """

        self._create_time = create_time

    @property
    def update_time(self) -> datetime:
        """
        Gets the update_time of this ApiNote.
        Output only. The time this note was last updated. This field can be used as a filter in list requests.

        :return: The update_time of this ApiNote.
        :rtype: datetime
        """
        return self._update_time

    @update_time.setter
    def update_time(self, update_time: datetime):
        """
        Sets the update_time of this ApiNote.
        Output only. The time this note was last updated. This field can be used as a filter in list requests.

        :param update_time: The update_time of this ApiNote.
        :type update_time: datetime
        """

        self._update_time = update_time

    @property
    def vulnerability_type(self) -> VulnerabilityType:
        """
        Gets the vulnerability_type of this ApiNote.
        A package vulnerability type of note.

        :return: The vulnerability_type of this ApiNote.
        :rtype: VulnerabilityType
        """
        return self._vulnerability_type

    @vulnerability_type.setter
    def vulnerability_type(self, vulnerability_type: VulnerabilityType):
        """
        Sets the vulnerability_type of this ApiNote.
        A package vulnerability type of note.

        :param vulnerability_type: The vulnerability_type of this ApiNote.
        :type vulnerability_type: VulnerabilityType
        """

        self._vulnerability_type = vulnerability_type

    @property
    def security_finding_type(self) -> SecurityFindingType:
        """
        Gets the security_finding_type of this ApiNote.
        A security finding type of note.

        :return: The security_finding_type of this ApiNote.
        :rtype: SecurityFindingType
        """
        return self._security_finding_type

    @security_finding_type.setter
    def security_finding_type(self, security_finding_type: SecurityFindingType):
        """
        Sets the security_finding_type of this ApiNote.
        A security finding type of note.

        :param security_finding_type: The security_finding_type of this ApiNote.
        :type security_finding_type: SecurityFindingType
        """

        self._security_finding_type = security_finding_type

