# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.operation import Operation
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class DiscoveryDiscovered(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, operation: Operation=None):
        """
        DiscoveryDiscovered - a model defined in Swagger

        :param operation: The operation of this DiscoveryDiscovered.
        :type operation: Operation
        """
        self.swagger_types = {
            'operation': Operation
        }

        self.attribute_map = {
            'operation': 'operation'
        }

        self._operation = operation

    @classmethod
    def from_dict(cls, dikt) -> 'DiscoveryDiscovered':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DiscoveryDiscovered of this DiscoveryDiscovered.
        :rtype: DiscoveryDiscovered
        """
        return deserialize_model(dikt, cls)

    @property
    def operation(self) -> Operation:
        """
        Gets the operation of this DiscoveryDiscovered.
        Output only. An operation that indicates the status of the current scan.

        :return: The operation of this DiscoveryDiscovered.
        :rtype: Operation
        """
        return self._operation

    @operation.setter
    def operation(self, operation: Operation):
        """
        Sets the operation of this DiscoveryDiscovered.
        Output only. An operation that indicates the status of the current scan.

        :param operation: The operation of this DiscoveryDiscovered.
        :type operation: Operation
        """

        self._operation = operation

