# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class NoteRelatedUrl(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, url: str=None, label: str=None):
        """
        NoteRelatedUrl - a model defined in Swagger

        :param url: The url of this NoteRelatedUrl.
        :type url: str
        :param label: The label of this NoteRelatedUrl.
        :type label: str
        """
        self.swagger_types = {
            'url': str,
            'label': str
        }

        self.attribute_map = {
            'url': 'url',
            'label': 'label'
        }

        self._url = url
        self._label = label

    @classmethod
    def from_dict(cls, dikt) -> 'NoteRelatedUrl':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NoteRelatedUrl of this NoteRelatedUrl.
        :rtype: NoteRelatedUrl
        """
        return deserialize_model(dikt, cls)

    @property
    def url(self) -> str:
        """
        Gets the url of this NoteRelatedUrl.

        :return: The url of this NoteRelatedUrl.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """
        Sets the url of this NoteRelatedUrl.

        :param url: The url of this NoteRelatedUrl.
        :type url: str
        """

        self._url = url

    @property
    def label(self) -> str:
        """
        Gets the label of this NoteRelatedUrl.

        :return: The label of this NoteRelatedUrl.
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label: str):
        """
        Sets the label of this NoteRelatedUrl.

        :param label: The label of this NoteRelatedUrl.
        :type label: str
        """

        self._label = label

