# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.api_package_manager_location import ApiPackageManagerLocation
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class PackageManagerInstallation(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, name: str=None, location: List[ApiPackageManagerLocation]=None):
        """
        PackageManagerInstallation - a model defined in Swagger

        :param name: The name of this PackageManagerInstallation.
        :type name: str
        :param location: The location of this PackageManagerInstallation.
        :type location: List[ApiPackageManagerLocation]
        """
        self.swagger_types = {
            'name': str,
            'location': List[ApiPackageManagerLocation]
        }

        self.attribute_map = {
            'name': 'name',
            'location': 'location'
        }

        self._name = name
        self._location = location

    @classmethod
    def from_dict(cls, dikt) -> 'PackageManagerInstallation':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PackageManagerInstallation of this PackageManagerInstallation.
        :rtype: PackageManagerInstallation
        """
        return deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """
        Gets the name of this PackageManagerInstallation.
        Output only. The name of the installed package.

        :return: The name of this PackageManagerInstallation.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """
        Sets the name of this PackageManagerInstallation.
        Output only. The name of the installed package.

        :param name: The name of this PackageManagerInstallation.
        :type name: str
        """

        self._name = name

    @property
    def location(self) -> List[ApiPackageManagerLocation]:
        """
        Gets the location of this PackageManagerInstallation.
        All of the places within the filesystem versions of this package have been found.

        :return: The location of this PackageManagerInstallation.
        :rtype: List[ApiPackageManagerLocation]
        """
        return self._location

    @location.setter
    def location(self, location: List[ApiPackageManagerLocation]):
        """
        Sets the location of this PackageManagerInstallation.
        All of the places within the filesystem versions of this package have been found.

        :param location: The location of this PackageManagerInstallation.
        :type location: List[ApiPackageManagerLocation]
        """

        self._location = location

