# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.package_manager_architecture import PackageManagerArchitecture
from swagger_server.models.vulnerability_type_version import VulnerabilityTypeVersion
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class PackageManagerDistribution(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, cpe_uri: str=None, architecture: PackageManagerArchitecture=None, latest_version: VulnerabilityTypeVersion=None, maintainer: str=None, url: str=None, description: str=None):
        """
        PackageManagerDistribution - a model defined in Swagger

        :param cpe_uri: The cpe_uri of this PackageManagerDistribution.
        :type cpe_uri: str
        :param architecture: The architecture of this PackageManagerDistribution.
        :type architecture: PackageManagerArchitecture
        :param latest_version: The latest_version of this PackageManagerDistribution.
        :type latest_version: VulnerabilityTypeVersion
        :param maintainer: The maintainer of this PackageManagerDistribution.
        :type maintainer: str
        :param url: The url of this PackageManagerDistribution.
        :type url: str
        :param description: The description of this PackageManagerDistribution.
        :type description: str
        """
        self.swagger_types = {
            'cpe_uri': str,
            'architecture': PackageManagerArchitecture,
            'latest_version': VulnerabilityTypeVersion,
            'maintainer': str,
            'url': str,
            'description': str
        }

        self.attribute_map = {
            'cpe_uri': 'cpe_uri',
            'architecture': 'architecture',
            'latest_version': 'latest_version',
            'maintainer': 'maintainer',
            'url': 'url',
            'description': 'description'
        }

        self._cpe_uri = cpe_uri
        self._architecture = architecture
        self._latest_version = latest_version
        self._maintainer = maintainer
        self._url = url
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'PackageManagerDistribution':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PackageManagerDistribution of this PackageManagerDistribution.
        :rtype: PackageManagerDistribution
        """
        return deserialize_model(dikt, cls)

    @property
    def cpe_uri(self) -> str:
        """
        Gets the cpe_uri of this PackageManagerDistribution.
        The cpe_uri in [cpe format](https://cpe.mitre.org/specification/) denoting the package manager version distributing a package.

        :return: The cpe_uri of this PackageManagerDistribution.
        :rtype: str
        """
        return self._cpe_uri

    @cpe_uri.setter
    def cpe_uri(self, cpe_uri: str):
        """
        Sets the cpe_uri of this PackageManagerDistribution.
        The cpe_uri in [cpe format](https://cpe.mitre.org/specification/) denoting the package manager version distributing a package.

        :param cpe_uri: The cpe_uri of this PackageManagerDistribution.
        :type cpe_uri: str
        """

        self._cpe_uri = cpe_uri

    @property
    def architecture(self) -> PackageManagerArchitecture:
        """
        Gets the architecture of this PackageManagerDistribution.

        :return: The architecture of this PackageManagerDistribution.
        :rtype: PackageManagerArchitecture
        """
        return self._architecture

    @architecture.setter
    def architecture(self, architecture: PackageManagerArchitecture):
        """
        Sets the architecture of this PackageManagerDistribution.

        :param architecture: The architecture of this PackageManagerDistribution.
        :type architecture: PackageManagerArchitecture
        """

        self._architecture = architecture

    @property
    def latest_version(self) -> VulnerabilityTypeVersion:
        """
        Gets the latest_version of this PackageManagerDistribution.
        The latest available version of this package in this distribution channel.

        :return: The latest_version of this PackageManagerDistribution.
        :rtype: VulnerabilityTypeVersion
        """
        return self._latest_version

    @latest_version.setter
    def latest_version(self, latest_version: VulnerabilityTypeVersion):
        """
        Sets the latest_version of this PackageManagerDistribution.
        The latest available version of this package in this distribution channel.

        :param latest_version: The latest_version of this PackageManagerDistribution.
        :type latest_version: VulnerabilityTypeVersion
        """

        self._latest_version = latest_version

    @property
    def maintainer(self) -> str:
        """
        Gets the maintainer of this PackageManagerDistribution.
        A freeform string denoting the maintainer of this package.

        :return: The maintainer of this PackageManagerDistribution.
        :rtype: str
        """
        return self._maintainer

    @maintainer.setter
    def maintainer(self, maintainer: str):
        """
        Sets the maintainer of this PackageManagerDistribution.
        A freeform string denoting the maintainer of this package.

        :param maintainer: The maintainer of this PackageManagerDistribution.
        :type maintainer: str
        """

        self._maintainer = maintainer

    @property
    def url(self) -> str:
        """
        Gets the url of this PackageManagerDistribution.
        The distribution channel-specific homepage for this package.

        :return: The url of this PackageManagerDistribution.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """
        Sets the url of this PackageManagerDistribution.
        The distribution channel-specific homepage for this package.

        :param url: The url of this PackageManagerDistribution.
        :type url: str
        """

        self._url = url

    @property
    def description(self) -> str:
        """
        Gets the description of this PackageManagerDistribution.
        The distribution channel-specific description of this package.

        :return: The description of this PackageManagerDistribution.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """
        Sets the description of this PackageManagerDistribution.
        The distribution channel-specific description of this package.

        :param description: The description of this PackageManagerDistribution.
        :type description: str
        """

        self._description = description

