# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.package_manager_distribution import PackageManagerDistribution
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class PackageManagerPackage(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, name: str=None, distribution: List[PackageManagerDistribution]=None):
        """
        PackageManagerPackage - a model defined in Swagger

        :param name: The name of this PackageManagerPackage.
        :type name: str
        :param distribution: The distribution of this PackageManagerPackage.
        :type distribution: List[PackageManagerDistribution]
        """
        self.swagger_types = {
            'name': str,
            'distribution': List[PackageManagerDistribution]
        }

        self.attribute_map = {
            'name': 'name',
            'distribution': 'distribution'
        }

        self._name = name
        self._distribution = distribution

    @classmethod
    def from_dict(cls, dikt) -> 'PackageManagerPackage':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PackageManagerPackage of this PackageManagerPackage.
        :rtype: PackageManagerPackage
        """
        return deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """
        Gets the name of this PackageManagerPackage.
        The name of the package.

        :return: The name of this PackageManagerPackage.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """
        Sets the name of this PackageManagerPackage.
        The name of the package.

        :param name: The name of this PackageManagerPackage.
        :type name: str
        """

        self._name = name

    @property
    def distribution(self) -> List[PackageManagerDistribution]:
        """
        Gets the distribution of this PackageManagerPackage.
        The various channels by which a package is distributed.

        :return: The distribution of this PackageManagerPackage.
        :rtype: List[PackageManagerDistribution]
        """
        return self._distribution

    @distribution.setter
    def distribution(self, distribution: List[PackageManagerDistribution]):
        """
        Sets the distribution of this PackageManagerPackage.
        The various channels by which a package is distributed.

        :param distribution: The distribution of this PackageManagerPackage.
        :type distribution: List[PackageManagerDistribution]
        """

        self._distribution = distribution

