#When gateway is in the same namespace 
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: grafeas-network-policy
  namespace: {{ index .Values.global.clusterNamespace .Values.global.env }}
spec:
  podSelector:
    matchLabels:
         microservice: grafeas
  ingress:
  - from:
    - podSelector:
       matchLabels: 
         microservice: findingsapi
    - podSelector:
       matchLabels:
         microservice: analyticsdistributor

    - podSelector:
       matchLabels:
         microservice: opsmgr
    - podSelector:
       matchLabels:
         microservice: findingscleaner
