apiVersion: v1
kind: Service
metadata:
   name: {{ .Values.global.name }}
   labels:
     microservice: {{ .Values.global.name }}
   namespace: {{ index .Values.global.clusterNamespace .Values.global.env }}
spec:
   ports:
   - port: 443
     targetPort: 443
     protocol: TCP
     name: http
   selector:
     microservice: {{ .Values.global.name }}
