apiVersion: v1
kind: ConfigMap
metadata:
  name: grafeas-configuration
  namespace: {{ index .Values.global.clusterNamespace .Values.global.env }}
data:
  logLevel: {{ index .Values.global.logLevel .Values.global.env | quote }}
  iamBaseUrl: {{ index .Values.global.iamBaseUrl .Values.global.env | quote }}
  iamApiBaseUrl: {{ index .Values.global.iamApiBaseUrl .Values.global.env | quote }}
  qradarHost: {{ index .Values.global.qradarHost .Values.global.env | quote }}
  acceptHttp: {{ index .Values.global.acceptHttp .Values.global.env  }}
  grafeasDB: {{ index .Values.global.grafeasDB .Values.global.env | quote }}
  certificateSecretMountPath: {{ .Values.global.certificateSecretMountPath | quote }}
  sslCertPath: {{ .Values.global.sslCertPath | quote }}
  sslKeyPath: {{ .Values.global.sslKeyPath | quote }}
  deleteOccurrencesPageSize: {{ .Values.global.deleteOccurrencesPageSize | quote }}
  grafeasConfigureSsl: {{ index .Values.global.grafeasConfigureSsl .Values.global.env }}
  grafeasAuthClassName: {{ index .Values.global.grafeasAuthClassName | quote }}

  {{ include "common-configuration" . | indent 2 }}