---
global:
  # env refers to the environment properties belong to during build-time. Default is "development".
  env: development

  # grafeas micro-service properties.
  name: grafeas
  tag:
  certificateSecretMountPath : /etc/secrets
  sslCertPath: /etc/secrets/tls_cert
  sslKeyPath: /etc/secrets/tls_key
  imageName:
    development: grafeas
    stage:
    pre_production:
    production:
  registryNamespace:
    development: secadvisor_dev
    stage:
    pre_production:
    production:
  registryHostName:
    development: registry.ng.bluemix.net
    stage:
    pre_production:
    production: registry.ng.bluemix.net
  log_level:
    development: debug
    stage: info
    pre_production: info
    production: info
  clusterNamespace:
    development: securityadvisor-dev-dal10
    stage:
    pre_production:
    production:
  grafeasDB:
    development: grafeas
    stage:
    pre_production:
    production:
  iamBaseUrl:
    development: https://iam.ng.bluemix.net
    stage:
    pre_production:
    production:
  iamApiBaseUrl:
    development: https://iam-api.ng.bluemix.net
    stage:
    pre_production:
    production:
  acceptHttp:
    development: '"true"'
    stage: '"false"'
    pre_production: '"false"'
    production: '"false"'
  grafeasConfigureSsl:
    development: '"true"'
    stage: '"true"'
    pre_production: '"true"'
    production: '"true"'
  qradarHost:
    development:
    stage:
    pre_production:
    production:
  grafeasUrl:
    development: https://25d6ed07-0aa0-4e8a-ab16-15c36aabe5f8-bluemix.cloudant.com
    stage:
    pre_production:
    production:
