---
global:
  # env refers to the environment properties belong to during build-time. Default is "development".
  env: development

  # grafeas micro-service properties.
  name: grafeas
  tag:
  certificateSecretMountPath : /etc/secrets
  sslCertPath: /etc/secrets/tls_cert
  sslKeyPath: /etc/secrets/tls_key
  deleteOccurrencesPageSize: 500
  grafeasAuthClassName: controllers.sa_auth.SecurityAdvisorAuthClient
  imageName:
    development: grafeas
    development_lon06: grafeas
    pre_production: grafeas
    pre_production_dal10: grafeas
    pre_production_dal12: grafeas
    pre_production_dal13: grafeas
    pre_production_lon02: grafeas
    pre_production_lon04: grafeas
    pre_production_lon05: grafeas
    production: grafeas
    production_dal10: grafeas
    production_dal12: grafeas
    production_dal13: grafeas
    production_lon02: grafeas
    production_lon04: grafeas
    production_lon05: grafeas

  registryHostName:
    development: registry.ng.bluemix.net
    development_lon06: registry.ng.bluemix.net    
    pre_production: registry.ng.bluemix.net
    pre_production_dal10: registry.ng.bluemix.net
    pre_production_dal12: registry.ng.bluemix.net
    pre_production_dal13: registry.ng.bluemix.net
    pre_production_lon02: registry.ng.bluemix.net
    pre_production_lon04: registry.ng.bluemix.net
    pre_production_lon05: registry.ng.bluemix.net    
    production: registry.ng.bluemix.net
    production_dal10: registry.ng.bluemix.net
    production_dal12: registry.ng.bluemix.net
    production_dal13: registry.ng.bluemix.net
    production_lon02: registry.ng.bluemix.net
    production_lon04: registry.ng.bluemix.net
    production_lon05: registry.ng.bluemix.net    

  logLevel:
    development: DEBUG
    development_lon06: DEBUG    
    pre_production: DEBUG
    pre_production_dal10: DEBUG
    pre_production_dal12: DEBUG
    pre_production_dal13: DEBUG
    pre_production_lon02: DEBUG
    pre_production_lon04: DEBUG
    pre_production_lon05: DEBUG    
    production: INFO
    production_dal10: INFO
    production_dal12: INFO
    production_dal13: INFO
    production_lon02: INFO
    production_lon04: INFO
    production_lon05: INFO

  grafeasDB:
    development: grafeas
    development_lon06: grafeas    
    pre_production: grafeaspreprod
    pre_production_dal10: grafeaspreprod
    pre_production_dal12: grafeaspreprod
    pre_production_dal13: grafeaspreprod
    pre_production_lon02: grafeaspreprod
    pre_production_lon04: grafeaspreprod
    pre_production_lon05: grafeaspreprod        
    production: grafeas
    production_dal10: grafeas
    production_dal12: grafeas
    production_dal13: grafeas
    production_lon02: grafeas
    production_lon04: grafeas
    production_lon05: grafeas

  iamBaseUrl:
    development: https://iam.ng.bluemix.net
    development_lon06: https://iam.ng.bluemix.net    
    stage:
    pre_production:
    pre_production_dal10: 
    pre_production_dal12: 
    pre_production_dal13: 
    pre_production_lon02: 
    pre_production_lon04: 
    pre_production_lon05:        
    production:
    production_dal10: 
    production_dal12: 
    production_dal13: 
    production_lon02: 
    production_lon04: 
    production_lon05: 

  iamApiBaseUrl:
    development: https://iam-api.ng.bluemix.net
    development_lon06: https://iam-api.ng.bluemix.net    
    stage:
    pre_production:
    pre_production_dal10: 
    pre_production_dal12: 
    pre_production_dal13: 
    pre_production_lon02: 
    pre_production_lon04: 
    pre_production_lon05:        
    production:
    production_dal10: 
    production_dal12: 
    production_dal13:
    production_lon02: 
    production_lon04: 
    production_lon05: 

  acceptHttp:
    development: '"true"'
    development_lon06: '"true"'    
    stage: '"false"'
    pre_production: '"false"'
    pre_production_dal10: '"false"'
    pre_production_dal12: '"false"'
    pre_production_dal13: '"false"'
    pre_production_lon02: '"false"'
    pre_production_lon04: '"false"'
    pre_production_lon05:  '"false"'      
    production: '"false"'
    production_dal10: '"false"'
    production_dal12: '"false"'
    production_dal13: '"false"'
    production_lon02: '"false"'
    production_lon04: '"false"'
    production_lon05: '"false"'

  grafeasConfigureSsl:
    development: '"true"'
    development_lon06: '"true"'    
    stage: '"true"'
    pre_production: '"true"'
    pre_production_dal10: '"true"'
    pre_production_dal12: '"true"'
    pre_production_dal13: '"true"'
    pre_production_lon02: '"true"'
    pre_production_lon04: '"true"'
    pre_production_lon05: '"true"'
    production: '"true"'
    production_dal10: '"true"'
    production_dal12: '"true"'
    production_dal13: '"true"'
    production_lon02: '"true"'
    production_lon04: '"true"'
    production_lon05: '"true"'

  qradarHost:
    development:
    development_lon06:    
    stage:
    pre_production:
    pre_production_dal10: 
    pre_production_dal12: 
    pre_production_dal13: 
    pre_production_lon02: 
    pre_production_lon04: 
    pre_production_lon05:   
    production:
    production_dal10: 
    production_dal12: 
    production_dal13: 
    production_lon02:
    production_lon04: 
    production_lon05:     

  grafeasUrl:
    development: https://25d6ed07-0aa0-4e8a-ab16-15c36aabe5f8-bluemix.cloudant.com
    development_lon06: https://25d6ed07-0aa0-4e8a-ab16-15c36aabe5f8-bluemix.cloudant.com    
    pre_production: https://25d6ed07-0aa0-4e8a-ab16-15c36aabe5f8-bluemix.cloudant.com
    pre_production_dal10: https://25d6ed07-0aa0-4e8a-ab16-15c36aabe5f8-bluemix.cloudant.com
    pre_production_dal12: https://25d6ed07-0aa0-4e8a-ab16-15c36aabe5f8-bluemix.cloudant.com
    pre_production_dal13: https://25d6ed07-0aa0-4e8a-ab16-15c36aabe5f8-bluemix.cloudant.com
    pre_production_lon02: https://25d6ed07-0aa0-4e8a-ab16-15c36aabe5f8-bluemix.cloudant.com
    pre_production_lon04: https://25d6ed07-0aa0-4e8a-ab16-15c36aabe5f8-bluemix.cloudant.com
    pre_production_lon05: https://25d6ed07-0aa0-4e8a-ab16-15c36aabe5f8-bluemix.cloudant.com
    production:
    production_dal10: 
    production_dal12: 
    production_dal13:
    production_lon02: 
    production_lon04: 
    production_lon05: 

    
