---
global:
  # env refers to the environment properties belong to during build-time. Default is "development".
  env: development

  # grafeas micro-service properties.
  name: grafeas
  tag:
  certificateSecretMountPath : /etc/secrets
  sslCertPath: /etc/secrets/tls_cert
  sslKeyPath: /etc/secrets/tls_key
  deleteOccurrencesPageSize: 500
  grafeasAuthClassName: controllers.sa_auth.SecurityAdvisorAuthClient
  imageName:
    development: grafeas
    development_lon06: grafeas
    pre_production: grafeas
    pre_production_dal10: grafeas
    pre_production_dal12: grafeas
    pre_production_dal13: grafeas
    pre_production_lon02: grafeas
    pre_production_lon04: grafeas
    pre_production_lon05: grafeas
    production: grafeas
    production_dal10: grafeas
    production_dal12: grafeas
    production_dal13: grafeas
    production_lon02: grafeas
    production_lon04: grafeas
    production_lon05: grafeas

  registryHostName:
    development: us.icr.io
    development_lon06: us.icr.io    
    pre_production: us.icr.io
    pre_production_dal10: us.icr.io
    pre_production_dal12: us.icr.io
    pre_production_dal13: us.icr.io
    pre_production_lon02: us.icr.io
    pre_production_lon04: us.icr.io
    pre_production_lon05: us.icr.io    
    production: us.icr.io
    production_dal10: us.icr.io
    production_dal12: us.icr.io
    production_dal13: us.icr.io
    production_lon02: us.icr.io
    production_lon04: us.icr.io
    production_lon05: us.icr.io    

  logLevel:
    development: DEBUG
    development_lon06: DEBUG    
    pre_production: DEBUG
    pre_production_dal10: DEBUG
    pre_production_dal12: DEBUG
    pre_production_dal13: DEBUG
    pre_production_lon02: DEBUG
    pre_production_lon04: DEBUG
    pre_production_lon05: DEBUG    
    production: INFO
    production_dal10: INFO
    production_dal12: INFO
    production_dal13: INFO
    production_lon02: INFO
    production_lon04: INFO
    production_lon05: INFO

  grafeasDB:
    development: grafeas
    development_lon06: grafeas    
    pre_production: grafeaspreprod
    pre_production_dal10: grafeaspreprod
    pre_production_dal12: grafeaspreprod
    pre_production_dal13: grafeaspreprod
    pre_production_lon02: grafeaspreprod
    pre_production_lon04: grafeaspreprod
    pre_production_lon05: grafeaspreprod        
    production: grafeas
    production_dal10: grafeas
    production_dal12: grafeas
    production_dal13: grafeas
    production_lon02: grafeas
    production_lon04: grafeas
    production_lon05: grafeas

  iamBaseUrl:
    development: https://iam.ng.bluemix.net
    development_lon06: https://iam.ng.bluemix.net    
    stage:
    pre_production:
    pre_production_dal10: 
    pre_production_dal12: 
    pre_production_dal13: 
    pre_production_lon02: 
    pre_production_lon04: 
    pre_production_lon05:        
    production:
    production_dal10: 
    production_dal12: 
    production_dal13: 
    production_lon02: 
    production_lon04: 
    production_lon05: 

  iamApiBaseUrl:
    development: https://iam-api.ng.bluemix.net
    development_lon06: https://iam-api.ng.bluemix.net    
    stage:
    pre_production:
    pre_production_dal10: 
    pre_production_dal12: 
    pre_production_dal13: 
    pre_production_lon02: 
    pre_production_lon04: 
    pre_production_lon05:        
    production:
    production_dal10: 
    production_dal12: 
    production_dal13:
    production_lon02: 
    production_lon04: 
    production_lon05: 

  acceptHttp:
    development: '"true"'
    development_lon06: '"true"'    
    stage: '"false"'
    pre_production: '"false"'
    pre_production_dal10: '"false"'
    pre_production_dal12: '"false"'
    pre_production_dal13: '"false"'
    pre_production_lon02: '"false"'
    pre_production_lon04: '"false"'
    pre_production_lon05:  '"false"'      
    production: '"false"'
    production_dal10: '"false"'
    production_dal12: '"false"'
    production_dal13: '"false"'
    production_lon02: '"false"'
    production_lon04: '"false"'
    production_lon05: '"false"'

  grafeasConfigureSsl:
    development: '"true"'
    development_lon06: '"true"'    
    stage: '"true"'
    pre_production: '"true"'
    pre_production_dal10: '"true"'
    pre_production_dal12: '"true"'
    pre_production_dal13: '"true"'
    pre_production_lon02: '"true"'
    pre_production_lon04: '"true"'
    pre_production_lon05: '"true"'
    production: '"true"'
    production_dal10: '"true"'
    production_dal12: '"true"'
    production_dal13: '"true"'
    production_lon02: '"true"'
    production_lon04: '"true"'
    production_lon05: '"true"'

  qradarHost:
    development:
    development_lon06:    
    stage:
    pre_production:
    pre_production_dal10: 
    pre_production_dal12: 
    pre_production_dal13: 
    pre_production_lon02: 
    pre_production_lon04: 
    pre_production_lon05:   
    production:
    production_dal10: 
    production_dal12: 
    production_dal13: 
    production_lon02:
    production_lon04: 
    production_lon05:

  globalScopeServices:
    development: iam-ServiceId-6dfe5ad0-5e48-48cf-9a2f-bfa861585570,iam-ServiceId-356c4bf2-e464-4f42-ab98-d4ac38f5e272,iam-ServiceId-5f4ca4ac-9a64-4bf0-ae03-4ad9a21afe42
    development_lon06: iam-ServiceId-6dfe5ad0-5e48-48cf-9a2f-bfa861585570,iam-ServiceId-356c4bf2-e464-4f42-ab98-d4ac38f5e272,iam-ServiceId-5f4ca4ac-9a64-4bf0-ae03-4ad9a21afe42
    stage: iam-ServiceId-6dfe5ad0-5e48-48cf-9a2f-bfa861585570,iam-ServiceId-7f9b9b0c-9deb-4a99-8d0e-823796519f3e,iam-ServiceId-5f4ca4ac-9a64-4bf0-ae03-4ad9a21afe42
    pre_production: iam-ServiceId-6dfe5ad0-5e48-48cf-9a2f-bfa861585570,iam-ServiceId-7f9b9b0c-9deb-4a99-8d0e-823796519f3e,iam-ServiceId-5f4ca4ac-9a64-4bf0-ae03-4ad9a21afe42
    pre_production_dal10: iam-ServiceId-6dfe5ad0-5e48-48cf-9a2f-bfa861585570,iam-ServiceId-7f9b9b0c-9deb-4a99-8d0e-823796519f3e,iam-ServiceId-5f4ca4ac-9a64-4bf0-ae03-4ad9a21afe42
    pre_production_dal12: iam-ServiceId-6dfe5ad0-5e48-48cf-9a2f-bfa861585570,iam-ServiceId-7f9b9b0c-9deb-4a99-8d0e-823796519f3e,iam-ServiceId-5f4ca4ac-9a64-4bf0-ae03-4ad9a21afe42
    pre_production_dal13: iam-ServiceId-6dfe5ad0-5e48-48cf-9a2f-bfa861585570,iam-ServiceId-7f9b9b0c-9deb-4a99-8d0e-823796519f3e,iam-ServiceId-5f4ca4ac-9a64-4bf0-ae03-4ad9a21afe42
    pre_production_lon02: iam-ServiceId-6dfe5ad0-5e48-48cf-9a2f-bfa861585570,iam-ServiceId-7f9b9b0c-9deb-4a99-8d0e-823796519f3e,iam-ServiceId-5f4ca4ac-9a64-4bf0-ae03-4ad9a21afe42
    pre_production_lon04: iam-ServiceId-6dfe5ad0-5e48-48cf-9a2f-bfa861585570,iam-ServiceId-7f9b9b0c-9deb-4a99-8d0e-823796519f3e,iam-ServiceId-5f4ca4ac-9a64-4bf0-ae03-4ad9a21afe42
    pre_production_lon05: iam-ServiceId-6dfe5ad0-5e48-48cf-9a2f-bfa861585570,iam-ServiceId-7f9b9b0c-9deb-4a99-8d0e-823796519f3e,iam-ServiceId-5f4ca4ac-9a64-4bf0-ae03-4ad9a21afe42
    production: iam-ServiceId-67312423-f05b-4c92-946a-28ce4487f15d,iam-ServiceId-20a97f8d-4e5a-452c-9b2a-26698c3bcb9a,iam-ServiceId-cb52855c-c610-4200-9ad8-13bb102a3867,iam-ServiceId-7b4398db-219e-4174-b4f5-c6e31970c7dc
    production_dal10: iam-ServiceId-67312423-f05b-4c92-946a-28ce4487f15d,iam-ServiceId-20a97f8d-4e5a-452c-9b2a-26698c3bcb9a,iam-ServiceId-cb52855c-c610-4200-9ad8-13bb102a3867,iam-ServiceId-7b4398db-219e-4174-b4f5-c6e31970c7dc
    production_dal12: iam-ServiceId-67312423-f05b-4c92-946a-28ce4487f15d,iam-ServiceId-20a97f8d-4e5a-452c-9b2a-26698c3bcb9a,iam-ServiceId-cb52855c-c610-4200-9ad8-13bb102a3867,iam-ServiceId-7b4398db-219e-4174-b4f5-c6e31970c7dc
    production_dal13: iam-ServiceId-67312423-f05b-4c92-946a-28ce4487f15d,iam-ServiceId-20a97f8d-4e5a-452c-9b2a-26698c3bcb9a,iam-ServiceId-cb52855c-c610-4200-9ad8-13bb102a3867,iam-ServiceId-7b4398db-219e-4174-b4f5-c6e31970c7dc
    production_lon02: iam-ServiceId-67312423-f05b-4c92-946a-28ce4487f15d,iam-ServiceId-20a97f8d-4e5a-452c-9b2a-26698c3bcb9a,iam-ServiceId-cb52855c-c610-4200-9ad8-13bb102a3867,iam-ServiceId-7b4398db-219e-4174-b4f5-c6e31970c7dc
    production_lon04: iam-ServiceId-67312423-f05b-4c92-946a-28ce4487f15d,iam-ServiceId-20a97f8d-4e5a-452c-9b2a-26698c3bcb9a,iam-ServiceId-cb52855c-c610-4200-9ad8-13bb102a3867,iam-ServiceId-7b4398db-219e-4174-b4f5-c6e31970c7dc
    production_lon05: iam-ServiceId-67312423-f05b-4c92-946a-28ce4487f15d,iam-ServiceId-20a97f8d-4e5a-452c-9b2a-26698c3bcb9a,iam-ServiceId-cb52855c-c610-4200-9ad8-13bb102a3867,iam-ServiceId-7b4398db-219e-4174-b4f5-c6e31970c7dc


    
